#' Create reports from evaluated tests
#' 
#' This is a rewrite of \code{klausur.report()} using RMarkdown instead of \LaTeX{}.
#'
#' If you want to use a certain value from the results slot in \code{klsr} in the code of \code{body}, you can use \code{\\newcommand} in your \code{template} and use the command in the markdown.
#'
#' @param klsr An object of class \code{klausuR}.
#' @param matn Either a single matriculation number (numeric), "all" (produces individuall documents for all subjects), "anon" (produces anonymous feedback)
#'    or "glob" (produces a global results document).
#' @param path Directory path for generated files, see \code{save}, \code{pdf} and \code{statistics}. Defaults to \code{meta[["out_dir"]]} if missing.
#' @param file_name Character vector, either defining the output file name directly (if \code{matn="anon"} or \code{matn="glob"}), or defining the column names of the results slot in \code{klsr} whose
#'    values should be used to create individual file names.
#' @param also_valid Character vector, values for \code{file_name} that should also be considered valid even if not column names of the results slot in \code{klsr}. They will be used as-is.
#' @param save Logical, if \code{TRUE}, all files, including intermediate RMarkdown files, are saved to \code{path}.
#'    If \code{save} is \code{FALSE}, a temporary directory is used.
#' @param pdf Logical, if \code{TRUE}, RMarkdown reports will be converted to PDF automatically, using \code{\link[rmarkdown:render]{rmarkdown::render}}.
#'    If \code{save} is \code{FALSE}, only the resulting PDF files are saved to \code{path}.
#' @param body Path to an RMarkdown template file that contains the lower body of the document (no YAML header!). If missing, a default template from
#'    \code{rmarkdown/templates/reports/resources/} of the installed package will be used, depending on the value of \code{matn}.
#' @param template Path to a Pandoc \code{.latex} template file. If missing, a default template from \code{rmarkdown/templates/reports/resources/} of
#'    the installed package will be used, depending on the value of \code{matn}.
#' @param header A list of variables to be defined in the YAML header of each RMarkdown file to be available for use in \code{template}.
#'    Lists of lists are supported, see \code{\link[yaml:as_yaml]{yaml::as_yaml}} for details.
#'    All headers automatically include the \code{meta} values named \code{title}, \code{lang} and \code{labels}, as well as a nested variable \code{test}
#'    includeing the variables \code{docent} (\code{meta}[["name"]]) and \code{date} (formatted \code{meta}[["date"]]).
#'    For individual reports, \code{header} will get a nested variable named \code{results} including all variables/columns of the results slot in \code{klsr} with their respective values
#'    of the row matching \code{matn}.
#' @param statistics Logical vector with recognized elements \code{hist_points}, \code{hist_marks}, \code{marks_points}, and \code{marks_percent}, indicating whether history plots for the
#'    distribution of points and marks or a table showing the marks grading scale should be included, including points, percent, or both. Missing elements default to \code{FALSE}.
#'    Histograms are also saved to \code{path} in PDF format.
#' @param plot_names Character vector with recognized entries \code{hist_points} and \code{hist_marks}, defining the file names for the histogram of points and marks respectively.
#' @param tablesize Character string to shrink the tables, must be one of \code{"auto"} (default), \code{"normalsize"}, \code{"small"},
#'    \code{"footnotesize"}, \code{"scriptsize"} or \code{"tiny"}. The default tries to decide between \code{"normalsize"} and \code{"footnotesize"}
#'    to avoid pages with only one or two rows. If that fails, try to manually set the size.
#' @param decreasing Logical, whether sorting of output should be done increasing or decreasing (only relevant for \code{matn = "anon"} or
#'    \code{matn = "glob"}).
#' @param sort_by Character string naming a variable to sort the results by. Defaults to \code{"Points"} (only relevant for \code{matn = "anon"} or
#'    \code{matn = "glob"}).
#' @param meta A list generated by \code{\link[klausuR:klausur_meta]{klausur_meta}}. These elements are directly used in generated report documents if present:
#'    \itemize{
#'      \item{\code{title}: title of the test}
#'      \item{\code{name}: name of the lecturer applying the test}
#'      \item{\code{date_print}: the formatted date string}
#'      \item{\code{lang}: language to set internal defaults for \code{labels} (see below); set to "de" for reports in German, English is the default}
#'      \item{\code{labels}: list with recognized elements \code{p_main}, \code{p_xlab}, \code{p_ylab}, \code{m_main}, \code{m_xlab}, and \code{m_ylab},
#'        defining the main title and axis annotation of points and marks histograms, respectively; \code{points}, \code{percent}, \code{m_scale} and \code{dist}
#'        defining the labels to use for points, percent, marks grading scale and distribution of test results}
#'    }
#' @param ... Additional arguments, currently unused.
#' @importFrom parallel makeCluster parSapply stopCluster
#' @docType methods
#' @rdname report-methods
#' @export
setGeneric(
  "report",
  function(
      klsr
    , matn
    , path
    , file_name = "MatrNo"
    , also_valid = c(
          "_"
        , "-"
      )
    , save = FALSE
    , pdf = FALSE
    , body
    , template
    , header
    , statistics = c(
          hist_points = FALSE
        , hist_marks = FALSE
        , marks_points = FALSE
        , marks_percent = FALSE
      )
    , plot_names = c(
          hist_points = "hist_points.pdf"
        , hist_marks = "hist_marks.pdf"
      )
    , tablesize = c("auto", "normalsize", "small", "footnotesize", "scriptsize", "tiny")
    , decreasing = TRUE
    , sort_by = "Points"
    , merge = FALSE
    , quiet = FALSE
    , cores = getOption("cl.cores", 1)
    , meta
    , ...
  ) standardGeneric("report")
)

#' @docType methods
#' @aliases report,klausuR-method
#' @rdname report-methods
setMethod(
  "report",
  signature(klsr="klausuR"),
  function(
      klsr
    , matn
    , path
    , file_name = "MatrNo"
    , also_valid = c(
          "_"
        , "-"
      )
    , save = FALSE
    , pdf = FALSE
    , body
    , template
    , header
    , statistics = c(
          hist_points = FALSE
        , hist_marks = FALSE
        , marks_points = FALSE
        , marks_percent = FALSE
      )
    , plot_names = c(
          hist_points = "hist_points.pdf"
        , hist_marks = "hist_marks.pdf"
      )
    , tablesize = c("auto", "normalsize", "small", "footnotesize", "scriptsize", "tiny")
    , decreasing = TRUE
    , sort_by = "Points"
    , merge = FALSE
    , quiet = FALSE
    , cores = getOption("cl.cores", 1)
    , meta
    , ...
  ){

    dot_vars <- list(...)

    if(all(!is.numeric(matn), !identical(matn, "all"), !identical(matn, "anon"), !identical(matn, "glob"))){
      stop(simpleError("Value assigned to matn must be numeric, \"all\", \"anon\" or \"glob\"!"))
    } else {}

    if(all(missing(path), !missing(meta))){
      path <- meta[["out_dir"]]
    } else {}

    if(!dir.exists(path)){
      stop(simpleError(paste0("Output directory not found:\n  ", path)))
    } else {}

    tablesize <- match.arg(tablesize)

    if(matn %in% c("anon", "glob")){
      klsr <- sort(klsr, decreasing=decreasing, sort.by=sort_by)
    } else {}

    klsr_results  <- slot(klsr, "results")
    klsr_points   <- slot(klsr, "points")
    klsr_answ     <- slot(klsr, "answ")
    klsr_anon     <- slot(klsr, "anon")
    klsr_corr     <- slot(klsr, "corr")
    klsr_items    <- sort(names(klsr_corr))

    # for a nice printout, check number of needed digits for points.
    # e.g, if you can get 1/2 points, you'd need one digit. but we won't allow more than two!
    if(identical(round(klsr_points[,-1], digits=0), klsr_points[,-1])){
      print_digits <- 0
    } else if(identical(round(klsr_points[,-1], digits=1), klsr_points[,-1])){
      print_digits <- 1
    } else {
      print_digits <- 2
    }

    labels <- default_labels(
        labels = meta[["labels"]]
      , lang = meta[["lang"]]
    )

    if(missing(header)){
      header <- list()
    } else {}
    if(!is.null(meta[["lang"]])){
      header[["lang"]] <- meta[["lang"]]
    } else {}
    header[["labels"]] <- labels

    if(all(is.null(header[["title"]]), !is.null(meta[["title"]]))){
      header[["title"]] <- meta[["title"]]
    } else {}
    if(is.null(header[["test"]])){
      header[["test"]] <- list()
    } else {}
    if(all(is.null(header[["test"]][["docent"]]), !is.null(meta[["name"]]))){
      header[["test"]][["docent"]] <- meta[["name"]]
    } else {}
    if(all(is.null(header[["test"]][["date"]]), !is.null(meta[["date_print"]]))){
      header[["test"]][["date"]] <- meta[["date_print"]]
    } else {}

    use_marks_cols <- c(
        "Points" = isTRUE(statistics[["marks_points"]])
      , "Percent" = isTRUE(statistics[["marks_percent"]])
    )
    if(any(use_marks_cols)){
      klsr_marks <- slot(klsr, "marks.sum")[, names(use_marks_cols)[use_marks_cols], drop = FALSE]
      klsr_marks_colnames <- c(
          "Points" = ifelse(is.null(header[["labels"]][["points"]]), "Points", header[["labels"]][["points"]])
        , "Percent" = ifelse(is.null(header[["labels"]][["percent"]]), "Percent", header[["labels"]][["percent"]])
      )
      colnames(klsr_marks) <- klsr_marks_colnames[colnames(klsr_marks)][names(use_marks_cols)[use_marks_cols]]
    } else {
      klsr_marks <- NULL
    }

    use_files <- c()

    header[["plot_names"]] <- list()

    if(any(statistics)){
      use_statistics <- statistics[statistics]
      header[["statistics"]] <- list()
      show_hist <- grepl("^hist_.*", names(use_statistics))
      show_marks <- grepl("^marks_.*", names(use_statistics))
      if(any(show_hist)){
        header[["statistics"]][["hist"]] <- as.list(use_statistics[show_hist])
      } else {}
      if(any(show_marks)){
        header[["statistics"]][["marks"]] <- as.list(use_statistics[show_marks])
      } else {}

      # the stat_cols variable will be added to make templating easier
      # it includes one nested logical variable encoding the columns needed for the statistics:
      # - "h" for only one histogram
      # - "hh" for two histograms
      # - "hhm" for two histograms and a table (marks)
      # - "hm" for one histogram and a table
      # - "m" for only the table
      header[["stat_cols"]] <- list()
      stat_cols_varname <- paste0(
          paste0(
              rep("h", sum(show_hist))
            , collapse=""
          )
        , ifelse(any(show_marks), "m", "")
        , collapse=""
      )
      header[["stat_cols"]][[stat_cols_varname]] <- TRUE
    } else {}

    if(isTRUE(statistics[["hist_points"]])) {
      if(is.null(plot_names[["hist_points"]])){
        plot_names[["hist_points"]] <- "hist_points.pdf"
      } else {}
      header[["plot_names"]][["hist_points"]] <- plot_names[["hist_points"]]
    } else {}
    if(isTRUE(statistics[["hist_marks"]])) {
      if(is.null(plot_names[["hist_marks"]])){
        plot_names[["hist_marks"]] <- "hist_marks.pdf"
      } else {}
      header[["plot_names"]][["hist_marks"]] <- plot_names[["hist_marks"]]
    } else {}

    if(!"rendered_plots" %in% names(dot_vars)){
      dot_vars[["rendered_plots"]] <- c()
      if(isTRUE(statistics[["hist_points"]])) {
        use_files[["hist_points"]] <- file.path(path, plot_names[["hist_points"]])
        dot_vars[["rendered_plots"]][["hist_points"]] <- plot_names[["hist_points"]]
        pdf(
            file=use_files[["hist_points"]]
          , width=10
          , height=10
          , pointsize=22
          , bg="white"
        )
        plot(
            klsr
          , xlab=labels[["p_xlab"]]
          , ylab=labels[["p_ylab"]]
          , main=labels[["p_main"]]
        )
        dev.off()
      } else {}

      if(isTRUE(statistics[["hist_marks"]])) {
        use_files[["hist_marks"]] <- file.path(path, plot_names[["hist_marks"]])
        dot_vars[["rendered_plots"]][["hist_marks"]] <- plot_names[["hist_marks"]]
        pdf(
            file=use_files[["hist_marks"]]
          , width=10
          , height=10
          , pointsize=22
          , bg="white"
        )
        plot(
            klsr
          , marks=TRUE
          , xlab=labels[["m_xlab"]]
          , ylab=labels[["m_ylab"]]
          , main=labels[["m_main"]]
        )
        dev.off()
      } else {}
    } else {
      if(!is.null(dot_vars[["rendered_plots"]][["hist_marks"]])){
        use_files[["hist_marks"]] <- file.path(path, plot_names[["hist_marks"]])
      } else {}
      if(!is.null(dot_vars[["rendered_plots"]][["hist_points"]])){
        use_files[["hist_points"]] <- file.path(path, plot_names[["hist_points"]])
      } else {}
    }

    if(identical(matn, "glob")){
      if (!isTRUE(quiet)){
        message(paste0("Processing: Global results"))
      } else {}

      this_file <- paste(file_name, sep="", collapse="")
      if(missing(template)){
        template <- system.file(
            file.path("rmarkdown", "templates", "reports", "resources", "template_global.latex")
          , package="klausuR"
        )
      } else {}
      if(missing(body)){
        body <- system.file(
            file.path("rmarkdown", "templates", "reports", "resources", "template_global_body.Rmd")
          , package="klausuR"
        )
      } else {}

      # define table size
      if(identical(tablesize, "auto")){
        if(nrow(klsr_results) > 37 & nrow(klsr_results) <= 45){
          # to avoid ugly tables with few lines on one page, shrink by heuristics
          header[["tablesize"]] <- "small"
        } else if(nrow(klsr_results) > 45 & nrow(klsr_results) < 50){
          header[["tablesize"]] <- "footnotesize"
        } else {
          header[["tablesize"]] <- "normalsize"
        }
      } else {
        header[["tablesize"]] <- tablesize
      }

      pre_body <- paste(
          "<!--"
        , "```{r setup, include=FALSE, echo=FALSE}"
        , paste0("global_df <- ", paste0(deparse(klsr_results), collapse="\n"), collapse="\n")
        , paste(
              "colnames_global <- c("
            , "    No = \"",        ifelse(is.null(header[["labels"]][["testno"]]),     "No",         header[["labels"]][["testno"]]), "\""
            , "  , Name = \"",      ifelse(is.null(header[["labels"]][["familyname"]]), "Name",       header[["labels"]][["familyname"]]), "\""
            , "  , FirstName = \"", ifelse(is.null(header[["labels"]][["firstname"]]),  "FirstName",  header[["labels"]][["firstname"]]), "\""
            , "  , MatrNo = \"",    ifelse(is.null(header[["labels"]][["matno_abbr"]]), "MatrNo",     header[["labels"]][["matno_abbr"]]), "\""
            , "  , Points = \"",    ifelse(is.null(header[["labels"]][["points"]]),     "Points",     header[["labels"]][["points"]]), "\""
            , "  , Percent = \"",   ifelse(is.null(header[["labels"]][["percent"]]),    "Percent",    header[["labels"]][["percent"]]), "\""
            , "  , Mark = \"",      ifelse(is.null(header[["labels"]][["mark"]]),       "Mark",       header[["labels"]][["mark"]]), "\""
            , "  , Pseudonym = \"", ifelse(is.null(header[["labels"]][["pseudonym"]]),  "Pseudonym",  header[["labels"]][["pseudonym"]]), "\""
            , ")"
            , sep="\n"
          )
          , paste0("colnames(global_df) <- colnames_global[colnames(global_df)]")
        , "```"
        , "-->\n\n"
        , sep = "\n"
      )
    } else if(identical(matn, "anon")) {
      if (!isTRUE(quiet)){
        message(paste0("Processing: Anonymous feedback"))
      } else {}

      this_file <- paste(file_name, sep="", collapse="")
      if(missing(template)){
        template <- system.file(
            file.path("rmarkdown", "templates", "reports", "resources", "template_anonymous.latex")
          , package="klausuR"
        )
      } else {}
      if(missing(body)){
        body <- system.file(
            file.path("rmarkdown", "templates", "reports", "resources", "template_anonymous_body.Rmd")
          , package="klausuR"
        )
      } else {}

      # define table size
      if(identical(tablesize, "auto")){
        if(nrow(klsr_anon) > 37 & nrow(klsr_anon) <= 45){
          # to avoid ugly tables with few lines on one page, shrink by heuristics
          header[["tablesize"]] <- "small"
        } else if(nrow(klsr_anon) > 45 & nrow(klsr_anon) < 50){
          header[["tablesize"]] <- "footnotesize"
        } else {
          header[["tablesize"]] <- "normalsize"
        }
      } else {
        header[["tablesize"]] <- tablesize
      }

      # remove rownames in case someone has memory of the running number of other students
      rownames(klsr_anon) <- NULL

      pre_body <- paste(
          "<!--"
        , "```{r setup, include=FALSE, echo=FALSE}"
        , paste0("anonymous_df <- ", paste0(deparse(klsr_anon), collapse="\n"), collapse="\n")
        , paste(
              "colnames_anon <- c("
            , "    Pseudonym = \"", ifelse(is.null(header[["labels"]][["pseudonym"]]),  "Pseudonym",  header[["labels"]][["pseudonym"]]), "\""
            , "  , Points = \"",    ifelse(is.null(header[["labels"]][["points"]]),     "Points",     header[["labels"]][["points"]]), "\""
            , "  , Percent = \"",   ifelse(is.null(header[["labels"]][["percent"]]),    "Percent",    header[["labels"]][["percent"]]), "\""
            , "  , Mark = \"",      ifelse(is.null(header[["labels"]][["mark"]]),       "Mark",       header[["labels"]][["mark"]]), "\""
            , ")"
            , sep="\n"
          )
          , paste0("colnames(anonymous_df) <- colnames_anon[colnames(anonymous_df)]")
        , "```"
        , "-->\n\n"
        , sep = "\n"
      )
    } else {
      if(missing(template)){
        template <- system.file(
            file.path("rmarkdown", "templates", "reports", "resources", "template_individual.latex")
          , package="klausuR"
        )
      } else {}
      if(missing(body)){
        body <- system.file(
            file.path("rmarkdown", "templates", "reports", "resources", "template_individual_body.Rmd")
          , package="klausuR"
        )
      } else {}

      if(identical(matn, "all")) {
        if(cores > 1){
          cl <- parallel::makeCluster(cores)
          if (!isTRUE(quiet)){
            message(paste0("Processing: Individual results (using ", cores, " cores)"))
          } else {}
          parallel::parSapply(
              cl = cl
            , klsr_results[["MatrNo"]]
            , function(this_matn){
                report(
                    klsr = klsr
                  , matn = this_matn
                  , path = path
                  , file_name = file_name
                  , also_valid = also_valid
                  , save = save
                  , pdf = pdf
                  , body = body
                  , template = template
                  , header = header
                  , statistics = statistics
                  , plot_names = plot_names
                  , tablesize = tablesize
                  , decreasing = decreasing
                  , sort_by = sort_by
                  , merge = merge
                  , quiet = quiet
                  , cores = 1
                  , meta = meta
                  , rendered_plots = dot_vars[["rendered_plots"]]
                  , ...
                )
              }
          )
          parallel::stopCluster(cl = cl)
        } else {
          sapply(
              klsr_results[["MatrNo"]]
            , function(this_matn){
                report(
                    klsr = klsr
                  , matn = this_matn
                  , path = path
                  , file_name = file_name
                  , also_valid = also_valid
                  , save = save
                  , pdf = pdf
                  , body = body
                  , template = template
                  , header = header
                  , statistics = statistics
                  , plot_names = plot_names
                  , tablesize = tablesize
                  , decreasing = decreasing
                  , sort_by = sort_by
                  , merge = merge
                  , quiet = quiet
                  , cores = 1
                  , meta = meta
                  , rendered_plots = dot_vars[["rendered_plots"]]
                  , ...
                )
              }
          )
        }
        if(all(isTRUE(merge), isTRUE(pdf))){
          merge_reports(
              results = klsr_results
            , labels = labels
            , descr = list(title=header[["title"]], name=header[["test"]][["docent"]], date=header[["test"]][["date"]])
            , file_name = file_name
            , also_valid = also_valid
            , pdf = pdf
            , path = path
            , save = save
            , quiet = quiet
            , fancyhdr = fancyhdr
          )
        } else {}
        return("done.")
      } else {
        this_file <- filename_from_df(
            matn = matn
          , file_name = file_name
          , also_valid = also_valid
          , df=klsr_results
        )

        header[["results"]] <- as.list(as.character(klsr_results[klsr_results[["MatrNo"]] == matn,]))
        names(header[["results"]]) <- colnames(klsr_results)

        if (!isTRUE(quiet)){
          # give some feedback on current status
          message(paste0("Processing: ", header[["results"]][["FirstName"]], " ", header[["results"]][["Name"]], " (", matn, ")"))
        } else {}

        # define table size
        if(identical(tablesize, "auto")){
          if(length(klsr_items) > 37 & length(klsr_items) <= 45){
            # to avoid ugly tables with few lines on one page, shrink by heuristics
            header[["tablesize"]] <- "small"
          } else if(length(klsr_items) > 45 & length(klsr_items) < 50){
            header[["tablesize"]] <- "footnotesize"
          } else {
            header[["tablesize"]] <- "normalsize"
          }
        } else {
          header[["tablesize"]] <- tablesize
        }

        pre_body <- paste(
            "```{r setup, include=FALSE, echo=FALSE}"
          , paste0("results <- ", paste0(deparse(header[["results"]]), collapse="\n"), collapse="\n")
          , paste0("correct <- ", paste0(deparse(klsr_corr), collapse="\n"), collapse="\n")
          , paste0("answers <- ", paste0(deparse(unlist(klsr_answ[klsr_answ[["MatrNo"]] == matn, klsr_items])), collapse="\n"), collapse="\n")
          , paste0("points <- ", paste0(deparse(unlist(klsr_points[klsr_points[["MatrNo"]] == matn, klsr_items])), collapse="\n"), collapse="\n")
          , paste0("marks <- ", paste0(deparse(klsr_marks), collapse="\n"), collapse="\n")
          , "all_items <- sort(names(correct))"
          , paste0(
                "results_df <- data.frame(\""
              , ifelse(is.null(header[["labels"]][["answer"]]), "Answer", header[["labels"]][["answer"]]), "\"=answers[all_items], \""
              , ifelse(is.null(header[["labels"]][["correct"]]), "Correct", header[["labels"]][["correct"]]), "\"=correct[all_items], \""
              , ifelse(is.null(header[["labels"]][["points"]]), "Points", header[["labels"]][["points"]]), "\"=points[all_items], row.names=all_items)"
              , collapse=""
            )
          , ifelse(
              length(names(use_files)) > 0,
              paste0("plot_names <- c(", paste0(names(use_files), "=\"", plot_names[names(use_files)],  collapse="\", "), "\")", collapse="\n"),
              paste0("plot_names <- c()")
            )
          , paste0("statistics <- ", paste0(deparse(statistics), collapse="\n"), collapse="\n")
          , "```\n\n"
          , sep = "\n"
        )
      }
    }

    write_markdown(
        file = paste0(this_file, ".Rmd")
      , path = path
      , header = header
      , pre_body = pre_body
      , body = body
      , template = template
      , save = save
      , pdf = pdf
      , use_files = use_files
    )

    return(invisible(NULL))
})

## TODO: report method for list

## TODO: report method for klausuR.mult
