#' Create reports from evaluated tests
#' 
#' This is a rewrite of \code{klausur.report()} using RMarkdown instead of \LaTeX{}.
#'
#' If you want to use a certain value from the results slot in \code{klsr} in the code of \code{body}, you can use \code{\\newcommand} in your \code{template} and use the command in the markdown.
#'
#' @param klsr An object of class \code{klausuR}.
#' @param matn TODO
#' @param path TODO
#' @param file_name Character vector, either defining the output file name directly (if \code{matn="anon"} or \code{matn="glob"}), or defining the column names of the results slot in \code{klsr} whose
#'    values should be used to create individual file names.
#' @param also_valid Character vector, values for \code{file_name} that should also be considered valid even if not column names of the results slot in \code{klsr}. They will be used as-is.
#' @param save TODO
#' @param pdf TODO
#' @param body TODO
#' @param template TODO
#' @param header A list of variables to be defined in the YAML header of each RMarkdown file to be available for use in \code{template}.
#'    Lists of lists are supported, see \code{\link[yaml:as_yaml]{yaml::as_yaml}} for details.
#'    For individual reports, \code{header} will get a nested variable named \code{results} including all variables/columns of the results slot in \code{klsr} with their respective values
#'    of the row matching \code{matn}. It will also include the \code{meta} values named \code{lang} and \code{labels}.
#' @param statistics Logical vector with recognized elements \code{hist_points}, \code{hist_marks}, \code{marks_points}, and \code{marks_percent}, indicating whether history plots for the
#'    distribution of points and marks or a table showing the marks grading scale should be included, including points, percent, or both. Missing elements default to \code{FALSE}.
#' @param plot_names Character vector with recognized entries \code{hist_points} and \code{hist_marks}, defining the file names for the histogram of points and marks respectively.
#' @param meta A list generated by \code{\link[klausuR:klausur_meta]{klausur_meta}}. These elements are directly used in generated report documents if present:
#'    \itemize{
#'      \item{\code{title}: title of the test}
#'      \item{\code{name}: name of the lecturer applying the test}
#'      \item{\code{date_print}: the formatted date string}
#'      \item{\code{lang}: language to set internal defaults for \code{labels} (see below); set to "de" for reports in German, English is the default}
#'      \item{\code{labels}: list with recognized elements \code{p_main}, \code{p_xlab}, \code{p_ylab}, \code{m_main}, \code{m_xlab}, and \code{m_ylab},
#'        defining the main title and axis annotation of points and marks histograms, respectively; \code{points}, \code{percent}, \code{m_scale} and \code{dist}
#'        defining the labels to use for points, percent, marks grading scale and distribution of test results}
#'    }
#' @param ... TODO
#' @docType methods
#' @rdname report-methods
#' @export
setGeneric(
  "report",
  function(
      klsr
    , matn
    , path
    , file_name = "MatrNo"
    , also_valid = c(
          "_"
        , "-"
      )
    , save = FALSE
    , pdf = FALSE
    , body
    , template
    , header
    , statistics = c(
          hist_points = FALSE
        , hist_marks = FALSE
        , marks_points = FALSE
        , marks_percent = FALSE
      )
    , plot_names = c(
          hist_points = "hist_points.pdf"
        , hist_marks = "hist_marks.pdf"
      )
    , meta
    , ...
  ) standardGeneric("report")
)

#' @docType methods
#' @aliases report,klausuR-method
#' @rdname report-methods
setMethod(
  "report",
  signature(klsr="klausuR"),
  function(
      klsr
    , matn
    , path
    , file_name = "MatrNo"
    , also_valid = c(
          "_"
        , "-"
      )
    , save = FALSE
    , pdf = FALSE
    , body
    , template
    , header
    , statistics = c(
          hist_points = FALSE
        , hist_marks = FALSE
        , marks_points = FALSE
        , marks_percent = FALSE
      )
    , plot_names = c(
          hist_points = "hist_points.pdf"
        , hist_marks = "hist_marks.pdf"
      )
    , meta
    , ...
  ){

    if(!dir.exists(path)){
      stop(simpleError(paste0("Output directory not found:\n  ", path)))
    } else {}

    klsr_results  <- slot(klsr, "results")
    klsr_points   <- slot(klsr, "points")
    klsr_answ     <- slot(klsr, "answ")
    klsr_anon     <- slot(klsr, "anon")
    klsr_corr     <- slot(klsr, "corr")

    labels <- default_labels(
        labels = meta[["labels"]]
      , lang = meta[["lang"]]
    )

    if(!is.null(meta[["lang"]])){
      header[["lang"]] <- meta[["lang"]]
    } else {}
    header[["labels"]] <- labels


    if(isTRUE(statistics[["hist_points"]])) {
      if(is.null(plot_names[["hist_points"]])){
        plot_names[["hist_points"]] <- "hist_points.pdf"
      } else {}
      pdf(
          file=file.path(path, plot_names[["hist_points"]])
        , width=10
        , height=10
        , pointsize=22
        , bg="white"
      )
      plot(
          klsr
        , xlab=labels[["p_xlab"]]
        , ylab=labels[["p_ylab"]]
        , main=labels[["p_main"]]
      )
      dev.off()
    } else {}

    if(isTRUE(statistics[["hist_marks"]])) {
      if(is.null(plot_names[["hist_marks"]])){
        plot_names[["hist_marks"]] <- "hist_marks.pdf"
      } else {}
      pdf(
          file=file.path(path, plot_names[["hist_marks"]])
        , width=10
        , height=10
        , pointsize=22
        , bg="white"
      )
      plot(
          klsr
        , marks=TRUE
        , xlab=labels[["m_xlab"]]
        , ylab=labels[["m_ylab"]]
        , main=labels[["m_main"]]
      )
      dev.off()
    } else {}

    if(identical(matn, "glob")){
      this_file <- paste(file_name, sep="", collapse="")
      if(missing(template)){
        template <- system.file(
            file.path("rmarkdown", "templates", "reports", "resources", "template_global.latex")
          , package="klausuR"
        )
      } else {}
      if(missing(body)){
        body <- system.file(
            file.path("rmarkdown", "templates", "reports", "resources", "template_global_body.Rmd")
          , package="klausuR"
        )
      } else {}
      pre_body <- paste(
          "<!--"
        , "```{r setup, include=FALSE, echo=FALSE}"
        , "```"
        , "-->\n\n"
        , sep = "\n"
      )
    } else if(identical(matn, "anon")) {
      this_file <- paste(file_name, sep="", collapse="")
      if(missing(template)){
        template <- system.file(
            file.path("rmarkdown", "templates", "reports", "resources", "template_anonymous.latex")
          , package="klausuR"
        )
      } else {}
      if(missing(body)){
        body <- system.file(
            file.path("rmarkdown", "templates", "reports", "resources", "template_anonymous_body.Rmd")
          , package="klausuR"
        )
      } else {}
      pre_body <- paste(
          "<!--"
        , "```{r setup, include=FALSE, echo=FALSE}"
        , "```"
        , "-->\n\n"
        , sep = "\n"
      )
    } else {
      if(missing(template)){
        template <- system.file(
            file.path("rmarkdown", "templates", "reports", "resources", "template_individual.latex")
          , package="klausuR"
        )
      } else {}
      if(missing(body)){
        body <- system.file(
            file.path("rmarkdown", "templates", "reports", "resources", "template_individual_body.Rmd")
          , package="klausuR"
        )
      } else {}

#       if(identical(matn, "all")) {
#         for(i in results[["MatrNo"]]){
#           ## loop
#         }
#         if(isTRUE(merge) & isTRUE(pdf)){
#           merge_reports(results=results, text=text, descr=descr, file.name=file.name, pdf=pdf, path=path, path.orig=path.orig, quiet=quiet, fancyhdr=fancyhdr)
#         } else {}
#       } else {
        this_file <- filename_from_df(
            matn = matn
          , file_name = file_name
          , also_valid = also_valid
          , df=klsr_results
        )

        header[["results"]] <- as.list(as.character(klsr_results[klsr_results[["MatrNo"]] == matn,]))
        names(header[["results"]]) <- colnames(klsr_results)

        pre_body <- paste(
            "```{r setup, include=FALSE, echo=FALSE}"
          , paste0("results <- ", paste0(deparse(header[["results"]]), collapse="\n"), collapse="\n")
          , paste0("correct <- ", paste0(deparse(klsr_corr), collapse="\n"), collapse="\n")
          , paste0("answers <- ", paste0(deparse(unlist(klsr_answ[klsr_answ[["MatrNo"]] == matn, names(klsr_corr)])), collapse="\n"), collapse="\n")
          , paste0("points <- ", paste0(deparse(unlist(klsr_points[klsr_points[["MatrNo"]] == matn, names(klsr_corr)])), collapse="\n"), collapse="\n")
          , "all_items <- sort(names(correct))"
          , paste0(
                "results_df <- data.frame(\""
              , ifelse(is.null(header[["labels"]][["answer"]]), "Answer", header[["labels"]][["answer"]]), "\"=answers[all_items], \""
              , ifelse(is.null(header[["labels"]][["correct"]]), "Correct", header[["labels"]][["correct"]]), "\"=correct[all_items], \""
              , ifelse(is.null(header[["labels"]][["points"]]), "Points", header[["labels"]][["points"]]), "\"=points[all_items], row.names=all_items)"
              , collapse=""
            )
          , "```\n\n"
          , sep = "\n"
        )
#       }
    }

    write_markdown(
        file = paste0(this_file, ".Rmd")
      , path = path
      , header = header
      , pre_body = pre_body
      , body = body
      , template = template
      , save = save
      , pdf = pdf
    )

    return(invisible(NULL))
})
