# This file was generated by roxyPackage::roxy.package()
# and will likely be overwritten on its next run.
# Editing is futile.

#' \packageDescription{klausuR}
#'
#' The DESCRIPTION file:
#' \tabular{ll}{
#' Package: \tab klausuR\cr
#' Type: \tab Package\cr
#' Version: \tab 0.13-1\cr
#' Date: \tab 2024-03-28\cr
#' Depends: \tab R (>= 2.9.0), xtable\cr
#' Enhances: \tab rkward\cr
#' Encoding: \tab UTF-8\cr
#' License: \tab GPL (>= 3)\cr
#' LazyLoad: \tab yes\cr
#' URL: \tab https://reaktanz.de/?c=hacking&s=klausuR\cr
#' }
#'
#' @title
#' \packageTitle{klausuR}
#' @author
#' \packageAuthor{klausuR}
#'
#' Maintainer: \packageMaintainer{klausuR}
"_PACKAGE"

## usethis namespace: start
## usethis namespace: end
NULL